name: Sb release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
    release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        - name: Setup Go
          uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
          with:
            go-version: '1.22.0'
        - run: go build -trimpath cmd/sb/sb.go
          env:
            GOOS: darwin
            GOARCH: arm64
            CGO_ENABLED: 0
        - run: gh release create $TAG -F changelog.md './sb#binary'
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TAG: ${{ github.ref }}
